using Microsoft.EntityFrameworkCore;
using Phonebook.Models;

namespace Phonebook;
internal class PhonebookContext: DbContext

{
    public DbSet<Contact> Contacts { get; set; } 
    public DbSet<Email> Emails { get; set; }
    public DbSet<Phone> PhoneNumbers { get; set; }
    public DbSet<EmailHistory> EmailHistory { get; set; }
    public DbSet<SMSHistory> SMSHistory { get; set; }
    public DbSet<Settings> Settings { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Configure IDENTITY_INSERT for the 'Settings' table
        modelBuilder.Entity<Settings>()
            .Property(s => s.SettingId)
            .ValueGeneratedNever(); // Ensure value is not generated by database (identity)
    }


    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) =>
    optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=Contacts;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Application Intent=ReadWrite;Multi Subnet Failover=False");
    

}
