// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Phonebook.Data.Contexts;

#nullable disable

namespace Phonebook.Data.Migrations
{
    [DbContext(typeof(SqlDatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Phonebook.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Default"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Friend"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Work"
                        });
                });

            modelBuilder.Entity("Phonebook.Data.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Contact");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Email = "john.smith@default.com",
                            Name = "John Smith",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Email = "mum@family.com",
                            Name = "Mum",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Email = "dad@family.com",
                            Name = "Dad",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Email = "bestie@friend.com",
                            Name = "Bestie",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Email = "boss@work.com",
                            Name = "Boss",
                            PhoneNumber = "1234567890"
                        });
                });

            modelBuilder.Entity("Phonebook.Data.Entities.Contact", b =>
                {
                    b.HasOne("Phonebook.Data.Entities.Category", "Category")
                        .WithMany("Contacts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Phonebook.Data.Entities.Category", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
