// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneBook.Data.Models;

#nullable disable

namespace PhoneBook.Migrations
{
    [DbContext(typeof(PhonebookDbContext))]
    [Migration("20241009123549_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhoneBook.Data.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            Name = "John Doe",
                            PhoneNumber = "555-123-4567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane.smith@example.com",
                            Name = "Jane Smith",
                            PhoneNumber = "555-987-6543"
                        },
                        new
                        {
                            Id = 3,
                            Email = "michael.johnson@example.com",
                            Name = "Michael Johnson",
                            PhoneNumber = "555-654-3210"
                        },
                        new
                        {
                            Id = 4,
                            Email = "emily.davis@example.com",
                            Name = "Emily Davis",
                            PhoneNumber = "555-876-5432"
                        },
                        new
                        {
                            Id = 5,
                            Email = "william.brown@example.com",
                            Name = "William Brown",
                            PhoneNumber = "555-432-1098"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
